/* Screen-specific visual system reconstructed from the approved W.O.L.F.E mockups. */
const v3Sheets={control:'assets/reference-homecontrol-v3.png',cameras:'assets/reference-cameras-v3.png'};
const v3Size={width:1680,height:945};
function spriteStyle(sheet,[x,y,w,h]){
  const sx=v3Size.width/w*100,sy=v3Size.height/h*100;
  const px=x/(v3Size.width-w)*100,py=y/(v3Size.height-h)*100;
  return `background-image:url('${v3Sheets[sheet]}');background-size:${sx}% ${sy}%;background-position:${px}% ${py}%`;
}
function v3Card(){return '';}
function v3Row(title,items,compact=false){return `<section class="row v3-row"><h2 class="rowTitle">${title} <span>›</span></h2><div class="cards">${items.map(item=>v3Card(item,compact)).join('')}</div></section>`;}
const homeContinue=[
  ['The Silent Peak','home',[32,419,262,108],'1h 12m left'],['The Ocean Within','home',[304,419,258,108],'42 min left'],['City of Shadows','home',[572,419,260,108],'S2 E3 · 28 min left'],['The Lost Kingdom','home',[842,419,259,108],'1h 4m left'],['Brighter Days','home',[1112,419,258,108],'28 min left'],['Spark','home',[1383,419,258,108],'15 min left']
];
const homeRecommended=[
  ['The Next Chapter','home',[35,569,260,85]],['The Good Life','home',[304,569,258,85]],['Shadow Protocol','home',[572,569,260,85]],['A Kinder World','home',[842,569,259,85]],['The Final Hour','home',[1112,569,258,85]],['Meet Again','home',[1383,569,258,85]]
];
const boxSets=[
  ['The Vanguard','home',[35,690,218,74]],['Riverdale Falls','home',[263,690,223,74]],['The Academy','home',[496,690,220,74]],['Planet Earth II','home',[726,690,223,74]],['Crimson Tide','home',[958,690,224,74]],['The Medic','home',[1192,690,220,74]],['The Medium','home',[1422,690,218,74]]
];
const onDemandContinue=[
  ['The Northridge','ondemand',[35,463,260,91],'1h 25m left'],['Skybound','ondemand',[305,463,258,91],'42 min left'],['The Meadows','ondemand',[574,463,258,91],'32 min left'],['Deep Current','ondemand',[844,463,260,91],'1h 10m left'],['Fractured Truth','ondemand',[1114,463,258,91],'28 min left'],['Solar Flare','ondemand',[1384,463,256,91],'45 min left']
];
const onDemandTrending=[
  ['Last Horizon','ondemand',[35,587,194,68]],['Emberfall','ondemand',[239,587,221,68]],['The Quiet Path','ondemand',[470,587,223,68]],['Orbital','ondemand',[702,587,220,68]],['Snowline','ondemand',[932,587,223,68]],['The Filament','ondemand',[1165,587,220,68]],['Wild Shores','ondemand',[1395,587,220,68]]
];
function serviceTiles(){return `<div class="v3-services"><button class="service-tile iptv focusable" onclick="openIptvPortal()"><b>▣</b><span>IPTV<small>On Demand</small></span></button><button class="service-tile netflix focusable" onclick="details('Netflix')"><b>N</b><span>NETFLIX</span></button><button class="service-tile disney focusable" onclick="details('Disney+')"><b>Disney+</b></button><button class="service-tile youtube focusable" onclick="details('YouTube')"><b>▶</b><span>YouTube</span></button></div>`;}
function openHomeControl(){app.tab='homecontrol';render();focusFirst();}
function smartPanel(){return `<section class="v3-smart"><div class="v3-panel-title">Smart Home <button class="panel-link focusable" onclick="openHomeControl()">Home Control ›</button></div><div class="smart-grid"><button class="smart-tile focusable" onclick="details('Living Room temperature')"><b>♨</b><strong>--°C</strong><small>Living Room</small></button><button class="smart-tile focusable" onclick="details('Kitchen temperature')"><b>♨</b><strong>--°C</strong><small>Kitchen</small></button><button class="smart-tile focusable" onclick="details('Lights')"><b>♧</b><strong>Lights</strong><small>Not connected</small></button><button class="smart-tile focusable" onclick="details('Security')"><b>♢</b><strong>Security</strong><small>Not connected</small></button><button class="smart-camera focusable" onclick="showCamera()"><span style="${spriteStyle('cameras',[585,232,522,225])}"></span><b>Front Door</b><small>Simulated preview</small></button></div></section>`;}
home=function(){
  const recommendationRows=typeof personalisedRecommendationRows==='function' ? personalisedRecommendationRows() : `${v3Row('Recommended for You',homeRecommended,true)}${v3Row('Popular Box Sets',boxSets,true)}`;
  $('content').innerHTML=`<div class="v3-page home-v3"><div class="v3-top-grid"><section class="v3-feature hero home-feature"><div class="heroCopy"><div class="eyebrow">FEATURED ON DEMAND</div><h1>YOUR LIBRARY</h1><h3>CONNECTING TO IPTV</h3><p>Your featured title will appear here from your on-demand library.</p><div class="feature-meta">On demand <i></i> Your IPTV library</div><div class="actions"><button class="primary focusable" onclick="openIptvPortal()">Browse on demand</button></div></div></section><aside class="home-side">${serviceTiles()}${smartPanel()}</aside></div>${v3Row('Continue Watching',homeContinue)}${recommendationRows}<div class="split-rows">${v3Row('Recently Added',homeRecommended.slice(0,4),true)}${v3Row('Family Favourites',homeRecommended.slice(3),true)}</div></div>`;
};
ondemand=function(){
  $('content').innerHTML=`<div class="v3-page ondemand-v3"><div class="v3-top-grid"><section class="v3-feature hero ondemand-feature"><div class="heroCopy"><div class="eyebrow">FEATURED ON DEMAND</div><h1>BEYOND<br>TOMORROW</h1><h3>SOME JOURNEYS CHANGE EVERYTHING</h3><p>A family’s extraordinary journey across new worlds reveals what truly matters.</p><div class="feature-meta">2024 <i></i> Adventure <i></i> 2h 12m <b>4K</b><b>HDR</b><b>5.1</b></div><div class="actions"><button class="primary focusable">▶ &nbsp; Watch Now</button><button class="secondary focusable" onclick="details('Beyond Tomorrow')">ⓘ &nbsp; More Info</button><button class="secondary focusable" onclick="details('Add Beyond Tomorrow to watchlist')">＋ &nbsp; Add to Watchlist</button></div></div></section><aside class="ondemand-side"><button class="search-box focusable" onclick="openUniversalSearch()">⌕ &nbsp; Search movies, series, or genres...</button><div class="side-actions"><button class="outline-tile focusable" onclick="details('Watchlist')">▱ <span>Watchlist<small>12 items</small></span>›</button><button class="outline-tile focusable" onclick="details('Last watched')">◷ <span>Last Watched<small>The Last Horizon</small></span>›</button></div>${smartPanel()}</aside></div><div class="filter-row">${['All','Movies','Box Sets','Recently Added','Favourites','4K','Family'].map((x,i)=>`<button class="filter ${i===0?'active':''} focusable">${x}</button>`).join('')}</div>${v3Row('Continue Watching',onDemandContinue)}${v3Row('Trending Movies',onDemandTrending,true)}${v3Row('Popular Box Sets',boxSets,true)}${v3Row('Recently Added',homeRecommended,true)}${v3Row('Family Picks',onDemandTrending.slice(0,6),true)}</div>`;
};
function libraryPage(title,subtitle,heroTitle,items){$('content').innerHTML=`<div class="v3-page library-v3"><div class="library-heading"><div class="eyebrow">W.O.L.F.E MEDIA</div><h1>${title}</h1><p>${subtitle}</p></div><div class="filter-row">${['Featured','Recently Added','Popular','Favourites','4K','Family'].map((x,i)=>`<button class="filter ${i===0?'active':''} focusable">${x}</button>`).join('')}</div>${v3Row('Continue Watching',items)}${v3Row(heroTitle,homeRecommended,true)}${v3Row('Popular Now',boxSets,true)}${v3Row('Recently Added',onDemandTrending,true)}</div>`;}
movies=function(){libraryPage('Movies','Browse films first, with live television kept out of the way.','Recommended Movies',onDemandContinue);};
series=function(){libraryPage('Series & Box Sets','Resume an episode or discover a complete box set.','Recommended Series',homeContinue);};
kids=function(){libraryPage('Kids','A bright, simple collection for younger profiles.','Family Favourites',onDemandContinue.slice().reverse());};
const roomData=[['Main Bedroom',[32,327,220,160]],['Bedroom 2',[264,327,219,160]],['Bedroom 3',[498,327,218,160]],['Bedroom 4',[731,327,215,160]],['Kitchen',[960,327,218,160]],['Living Room',[1193,327,218,160]],['Hallway',[1425,327,215,160]]];
homecontrol=function(){
  $('content').innerHTML=`<div class="v3-page control-v3"><section class="control-banner"><div><h1>WELCOME HOME</h1><h3>A SMARTER, BRIGHTER, SAFER HOME</h3><p>Comfort. Security. Peace of mind. Together.</p></div><div class="control-summary">${[['⌂','Home Mode','Home'],['♨','Home Temperature','--°C'],['◉','Heating Target','--°C'],['♢','Security Status','Not connected']].map(x=>`<button class="summary-tile focusable" onclick="details('${x[1]}')"><b>${x[0]}</b><small>${x[1]}</small><strong>${x[2]}</strong></button>`).join('')}</div></section><div class="section-heading"><h2>Rooms</h2><span>Home Assistant connection coming later</span></div><div class="room-cards">${roomData.map(([name,coords],i)=>`<button class="room-card focusable" onclick="details('${name}')"><span class="room-image" style="${spriteStyle('control',coords)}"></span><strong>${name}</strong><div><span>♨ --°C</span><span>♧ --</span><span>▣ --</span></div><small>Not connected</small></button>`).join('')}</div><h2>Quick Actions</h2><div class="action-grid">${[['▤','Movie Mode'],['☾','Bedtime'],['⌂','Away Mode'],['◯','All Off'],['☀','Good Morning']].map(x=>`<button class="action-card focusable" onclick="details('${x[1]}')"><b>${x[0]}</b><span><strong>${x[1]}</strong><small>Available after Home Assistant setup</small></span></button>`).join('')}</div><div class="overview-grid"><div><b>♧</b><span>Lighting Overview<strong>-- / --</strong><small>Not connected</small></span></div><div><b>♨</b><span>Thermostat Overview<strong>--°C</strong><small>Not connected</small></span></div></div></div>`;
};
const cameraData=[['Front Door',[35,231,530,228]],['Driveway',[585,231,523,228]],['Garden',[35,525,529,225]],['Side Gate',[585,525,523,225]]];
cameras=function(){
  $('content').innerHTML=`<div class="v3-page cameras-v3"><div class="camera-heading"><div><h1>CAMERAS</h1><p>PEACE OF MIND. ANYTIME. ANYWHERE.</p></div><div><b>TAPO CAMERAS</b><span>Integration reserved for later</span></div></div><div class="camera-layout"><div class="camera-grid">${cameraData.map(([name,coords],i)=>`<button class="camera-card focusable" onclick="showCamera()"><span class="camera-image" style="${spriteStyle('cameras',coords)}"></span><strong>${name}</strong><small><i></i> SIMULATED</small><em>${i<2?'2K':'1080p'}</em></button>`).join('')}</div><aside class="camera-side"><div class="camera-actions">${[['⛶','Full Screen'],['▶','Recordings'],['◉','Privacy Mode'],['☷','Events']].map(x=>`<button class="camera-action focusable" onclick="details('${x[1]}')"><b>${x[0]}</b><span>${x[1]}</span></button>`).join('')}</div><section class="events"><div class="v3-panel-title">Recent Events <span>View All</span></div>${cameraData.map(([name,coords],i)=>`<button class="event focusable" onclick="showCamera()"><span style="${spriteStyle('cameras',coords)}"></span><b>${name}<small>${i%2?'Vehicle':'Person'} detected</small></b><em>${['2 min ago','18 min ago','1 hour ago','3 hours ago'][i]}</em></button>`).join('')}</section></aside></div><div class="camera-footer"><b>♢</b><span>SMARTER HOME. SAFER TOGETHER.<small>Simulated views · Smart alerts · Recordings after integration</small></span></div></div>`;
};
apps=function(){$('content').innerHTML=`<div class="v3-page apps-v3"><div class="library-heading"><div class="eyebrow">W.O.L.F.E MEDIA</div><h1>Apps</h1><p>Your family services in one place.</p></div>${serviceTiles()}<div class="app-note">Official services open in their own secure website or installed Windows app. W.O.L.F.E does not store streaming passwords.</div></div>`;};
settings=function(){$('content').innerHTML=`<div class="v3-page settings-v3"><div class="library-heading"><div class="eyebrow">W.O.L.F.E MEDIA</div><h1>Settings</h1><p>Local prototype configuration.</p></div><div class="settings-grid"><button class="setting focusable" onclick="showProfiles()"><b>◉</b><span>Profiles<small>${app.profile} selected</small></span></button><button class="setting focusable" onclick="showProfileSetup(true)"><b>✦</b><span>Personalise ${app.profile}<small>Likes, age group and profile picture</small></span></button><button class="setting focusable" onclick="showIptvSetup()"><b>▣</b><span>IPTV setup<small>Connect an Xtream Codes provider</small></span></button><button class="setting focusable" onclick="showIptv()"><b>◫</b><span>IPTV connections<small>Two-slot local manager</small></span></button><button class="setting focusable" onclick="details('Integrations')"><b>⌁</b><span>Integrations<small>Home Assistant, Tapo and Alexa inactive</small></span></button></div></div>`;};
const homeControlButton=nav.querySelector('[data-tab="homecontrol"]');
if(homeControlButton)homeControlButton.textContent='Home Control';
let settingsButton=nav.querySelector('[data-tab="settings"]');
if(!settingsButton){settingsButton=document.createElement('button');settingsButton.className='nav focusable';settingsButton.dataset.tab='settings';settingsButton.textContent='Settings';settingsButton.onclick=()=>{app.tab='settings';render();focusFirst();};nav.appendChild(settingsButton);}
let searchButton=nav.querySelector('[data-tab="search"]');
if(!searchButton){searchButton=document.createElement('button');searchButton.className='nav focusable';searchButton.dataset.tab='search';searchButton.textContent='Search';searchButton.onclick=()=>openUniversalSearch();nav.appendChild(searchButton);}
['home','ondemand','movies','series','kids','cameras','homecontrol','apps','search','settings'].forEach(id=>{const button=nav.querySelector(`[data-tab="${id}"]`);if(button)nav.appendChild(button);});
const renderV2=render;
render=function(){if(app.tab==='settings'){profileUI();document.querySelectorAll('.nav').forEach(button=>button.classList.toggle('active',button.dataset.tab==='settings'));settings();focusFirst();}else renderV2();};
