const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { Store } = require('../services/media-server/src/store.cjs');
function setup(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'wolfe-test-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return new Store(path.join(dir,'state.json'));}
const acquire=(store,client)=>store.command({action:'acquire',client,profile:'Mike',title:'Demo',mode:'main'});
test('third client blocked; existing client retains one slot; release permits next client',t=>{const s=setup(t);acquire(s,'a');acquire(s,'b');assert.equal(acquire(s,'c').blocked,true);acquire(s,'a');assert.equal(s.state.slots.length,2);s.command({action:'release',client:'a'});assert.equal(acquire(s,'c').blocked,undefined);assert.equal(s.state.slots.length,2);});
test('expired clients are reclaimed',t=>{const s=setup(t);acquire(s,'a');acquire(s,'b');s.state.slots[0].expires=0;assert.equal(acquire(s,'c').blocked,undefined);});
test('profile progress persists separately and leases do not survive restart',t=>{const s=setup(t);s.command({action:'progress',client:'a',profile:'Mike',title:'Demo',percent:42});s.command({action:'progress',client:'b',profile:'Amy',title:'Demo',percent:13});acquire(s,'a');const restored=new Store(s.file);assert.equal(restored.state.progress.Mike.Demo.percent,42);assert.equal(restored.state.progress.Amy.Demo.percent,13);assert.equal(restored.state.slots.length,0);});
test('invalid profile and invalid progress rejected',t=>{const s=setup(t);assert.throws(()=>s.command({action:'progress',client:'a',profile:'Nobody',title:'Demo',percent:42}));assert.throws(()=>s.command({action:'progress',client:'a',profile:'Mike',title:'Demo',percent:NaN}));});
test('corrupt state is backed up and startup recovers',t=>{const s=setup(t);fs.writeFileSync(s.file,'broken');const restored=new Store(s.file);assert.deepEqual(restored.state.progress,{});assert.ok(fs.readdirSync(path.dirname(s.file)).some(f=>f.includes('.corrupt-')));});
test('bedroom profile request stays pending until approved and then persists',t=>{const s=setup(t);const device='12345678-1234-1234-1234-123456789abc';s.command({action:'requestProfileChange',client:'bedroom',device,profile:'Brooke',mode:'lite'});assert.equal(s.snapshot().profileRequests.length,1);const request=s.snapshot().profileRequests[0];s.command({action:'approveProfileChange',client:'main',requestId:request.id});assert.equal(s.snapshot().profileRequests.length,0);assert.equal(s.snapshot().profileAssignments[device].profile,'Brooke');const restored=new Store(s.file);assert.equal(restored.snapshot().profileAssignments[device].profile,'Brooke');});
test('watch events build separate profile history and local trending signals',t=>{const s=setup(t);s.command({action:'watch',client:'a',profile:'Mike',title:'A real title'});s.command({action:'watch',client:'b',profile:'Amy',title:'A real title'});assert.equal(s.snapshot().watchHistory.Mike['A real title'].count,1);assert.equal(s.snapshot().trending['A real title'].count,2);const restored=new Store(s.file);assert.equal(restored.snapshot().trending['A real title'].count,2);});
test('completed profile preferences persist across a local server restart',t=>{const s=setup(t);const preferences={completed:true,age:'Adult',genres:['Sci-Fi','Action'],moods:['New releases'],avatar:'wolf'};s.command({action:'saveProfilePreferences',client:'a',profile:'Mike',preferences});assert.deepEqual(s.snapshot().profilePreferences.Mike,preferences);const restored=new Store(s.file);assert.deepEqual(restored.snapshot().profilePreferences.Mike,preferences);});
test('invalid profile preferences are rejected',t=>{const s=setup(t);assert.throws(()=>s.command({action:'saveProfilePreferences',client:'a',profile:'Mike',preferences:{age:'Adult',genres:['Unknown'],moods:['New releases'],avatar:'wolf'}}));});
